server:
  port: 8083
spring:
  application:
    name: attendance
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    username: fleet
    password: 123456
    url: jdbc:mysql://192.168.5.73:3306/fleet_staging?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#redis配置
redis:
  # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
  database: 3
  # redis服务器地址（默认为localhost）
  host: localhost
  # redis端口（默认为6379）
  port: 6379
  # redis访问密码（默认为空）
  password:
  # redis连接超时时间（单位为毫秒）
  timeout: 1000
  # redis连接池配置
  jedis:
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

# mybatis配置
mybatis:
  # 映射xml的文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类所在包，简化xml中resultMap中实体类的全类名写法
  type-aliases-package: cn.flashexpress.attendance.entity

#日志
logging:
  config:
    classpath: logback-spring.xml

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
